name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build with Buildozer (community action)
        uses: digreatbrian/buildozer-action@v1
        with:
          buildozer-cmd: "android debug"
